# Generated by Django 5.2.4 on 2025-07-07 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution_number", models.CharField(max_length=100)),
                ("resolution_date", models.DateField()),
                ("issuing_authority", models.CharField(max_length=255)),
                ("received_date", models.DateField()),
                ("violation_date", models.DateField()),
                ("violation_time", models.TimeField()),
                ("violation_address", models.CharField(max_length=255)),
                ("car_model", models.CharField(max_length=100)),
                ("car_plate", models.CharField(max_length=10)),
                ("detection_method", models.CharField(max_length=100)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="complaint_photos/"
                    ),
                ),
                ("fine_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("controller_name", models.CharField(max_length=100)),
                ("parking_number", models.CharField(max_length=50)),
                ("serial_number", models.CharField(max_length=50)),
                ("certificate_number", models.CharField(max_length=50)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="complaints_pdfs/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
