# Generated by Django 5.2.4 on 2025-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="client_full_name",
            field=models.CharField(default="без имени", max_length=255),
            preserve_default=False,
        ),
    ]
