# Generated by Django 5.2.4 on 2025-07-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_legalcomplaint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legalcomplaint",
            old_name="inn",
            new_name="company_phone",
        ),
        migrations.RemoveField(
            model_name="legalcomplaint",
            name="contract_number",
        ),
        migrations.RemoveField(
            model_name="legalcomplaint",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="legalcomplaint",
            name="received_details",
        ),
        migrations.RemoveField(
            model_name="legalcomplaint",
            name="violation_description",
        ),
        migrations.AddField(
            model_name="legalcomplaint",
            name="attachment",
            field=models.FileField(default=1, upload_to="legal_attachments/"),
            preserve_default=False,
        ),
    ]
