# Generated by Django 5.2.4 on 2025-07-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_inn_legalcomplaint_company_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В обработке"),
                    ("accepted", "Принято"),
                    ("rejected", "Отклонено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус жалобы",
            ),
        ),
    ]
