# Generated by Django 5.2.4 on 2025-07-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_legalcomplaint_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="certificate_number",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="controller_name",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="parking_number",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="serial_number",
        ),
        migrations.AddField(
            model_name="complaint",
            name="violated_law_norm",
            field=models.CharField(
                default="Не указано",
                max_length=255,
                verbose_name="Нарушенная норма закона",
            ),
        ),
    ]
