# Generated by Django 5.2.4 on 2025-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_complaint_certificate_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="violated_law_norm",
            field=models.CharField(
                max_length=255, verbose_name="Нарушенная норма закона"
            ),
        ),
    ]
