# Generated by Django 5.2.4 on 2025-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_complaint_violated_law_norm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="violated_law_norm",
        ),
        migrations.AddField(
            model_name="complaint",
            name="certificate_number",
            field=models.CharField(default="ifshfis", max_length=50),
        ),
        migrations.AddField(
            model_name="complaint",
            name="controller_name",
            field=models.CharField(default="ifshfis", max_length=100),
        ),
        migrations.AddField(
            model_name="complaint",
            name="parking_number",
            field=models.CharField(default="ifshfis", max_length=50),
        ),
        migrations.AddField(
            model_name="complaint",
            name="serial_number",
            field=models.CharField(default="ifshfis", max_length=50),
        ),
    ]
