# Generated by Django 5.2.4 on 2025-07-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_complaint_violated_law_norm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="certificate_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="controller_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="parking_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="serial_number",
            field=models.CharField(max_length=50),
        ),
    ]
